easy_admin:
    entities:
        # List the entity class name you want to manage
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - title
                    - published
                    - slug
                    - textSource
                    - image
                    - tags
        Tag:
            class: App\Entity\Tag
    design:
        menu:
            - { entity: Article, label: Articles }
            - { entity: Tag, label: Tags }
            - { label: 'Open front-end', route: 'homepage' }
        assets:
            js:
                - '/js/admin.js'
