easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Article
        - App\Entity\Tag
    design:
        assets:
            js:
                - '/ckeditor/ckeditor.js'
                - '/js/admin.js'
