fos_comment:
  db_driver: orm
  acl: true
  class:
    model:
      comment: App\Entity\Comment
      thread: App\Entity\Thread
  service:
    acl:
      thread:  fos_comment.acl.thread.roles
      comment: fos_comment.acl.comment.roles
      vote:    fos_comment.acl.vote.roles
    manager:
      thread:  fos_comment.manager.thread.acl
      comment: fos_comment.manager.comment.acl
      vote:    fos_comment.manager.vote.acl
  acl_roles:
    comment:
      create: ROLE_USER
      view: IS_AUTHENTICATED_ANONYMOUSLY
      edit: ROLE_SUPER_ADMIN
      delete: ROLE_SUPER_ADMIN
    thread:
      create: IS_AUTHENTICATED_ANONYMOUSLY
      view: IS_AUTHENTICATED_ANONYMOUSLY
      edit: ROLE_SUPER_ADMIN
      delete: ROLE_SUPER_ADMIN
    vote:
      create: ROLE_USER
      view: IS_AUTHENTICATED_ANONYMOUSLY
      edit: ROLE_SUPER_ADMIN
      delete: ROLE_SUPER_ADMIN
