hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    use_referer: true
    connect:
        account_connector: App\Security\FOSUBUserProvider
    fosub:
        properties:
            github: githubId
    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        github:
            type:                github
            client_id:           '%env(GITHUB_ID)%'
            client_secret:       '%env(GITHUB_SECRET)%'
            scope:               'user:email,public_repo'
